import { Zone } from "./plant-info";

export function getZones(): Zone[] {
    return [
        { id: 0, name: ""},
        { id: 1, name: "1"},
        { id: 2, name: "1a"},
        { id: 3, name: "1b"},
        { id: 4, name: "2"},
        { id: 5, name: "2a"},
        { id: 6, name: "2b"},
        { id: 7, name: "3"},
        { id: 8, name: "3a"},
        { id: 9, name: "3b"},
        { id: 10, name: "4"},
        { id: 11, name: "4a"},
        { id: 12, name: "4b"},
        { id: 13, name: "5"},
        { id: 14, name: "5a"},
        { id: 15, name: "5b"},
        { id: 16, name: "6"},
        { id: 17, name: "6a"},
        { id: 18, name: "6b"},
        { id: 19, name: "7"},
        { id: 20, name: "7a"},
        { id: 21, name: "7b"},
        { id: 22, name: "8"},
        { id: 23, name: "8a"},
        { id: 24, name: "8b"},
        { id: 25, name: "9"},
        { id: 26, name: "9a"},
        { id: 27, name: "9b"},
        { id: 28, name: "10"},
        { id: 29, name: "10a"},
        { id: 30, name: "10b"},
        { id: 31, name: "11"},
        { id: 32, name: "11a"},
        { id: 33, name: "11b"},
        { id: 34, name: "12"},
        { id: 35, name: "12a"},
        { id: 36, name: "12b"},
        { id: 37, name: "13"},
        { id: 38, name: "13a"},
        { id: 39, name: "13b"}
    ];
}