namespace Emergence.Data.External.iNaturalist
{
    public enum Rank
    {
        Kingdom,
        Phylum,
        Subphylum,
        Superclass,
        Class,
        Subclass,
        Infraclass,
        Superorder,
        Order,
        Suborder,
        Infraorder,
        Superfamily,
        Epifamily,
        Family,
        Subfamily,
        Supertribe,
        Tribe,
        Subtribe,
        GenusHybrid,
        Genus,
        Subgenus,
        Hybrid,
        Species,
        Subspecies,
        Variety,
        Form,
        Section
    }
}
