name: Build and test Emergence functions

on:
  push:
    branches: [ dev ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ dev ]
    paths-ignore:
    - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Install dependencies
      run: dotnet restore Emergence.Functions.sln
      working-directory: src
    - name: Build
      run: dotnet build Emergence.Functions.sln --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test Emergence.Functions.sln --no-restore --verbosity normal
      working-directory: src
