name: Build and test Emergence web

on:
  push:
    branches: [ dev ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ dev ]
    paths-ignore:
    - 'docs/**'

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore Emergence.sln
      working-directory: src
    - name: Build
      run: dotnet build Emergence.sln --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test Emergence.sln --no-restore --verbosity normal
      working-directory: src
      
  build-fn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Install dependencies
      run: dotnet restore Emergence.Functions.sln
      working-directory: src
    - name: Build
      run: dotnet build Emergence.Functions.sln --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test Emergence.Functions.sln --no-restore --verbosity normal
      working-directory: src
