name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - name: Build with dotnet
      run: dotnet build Emergence.sln --configuration Release
      working-directory: src
      
    - name: dotnet publish
      run: dotnet publish Emergence.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp
      working-directory: src
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'emergenceapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d88b9164ffda4902a20e0ccd2ba03e4b }}
        package: ${{env.DOTNET_ROOT}}/myapp 
